export const globalActionTypes = {
  SET_LOADER: "SET_LOADER",
  SET_ERROR: "SET_ERROR"
};

export const worldActionTypes = {
  SET_XUR_DATA: "SET_XUR_DATA"
};
export const playerActionTypes = {
  SET_PLAYER_DATA: "SET_PLAYER_DATA",
  SET_XUR_DATA: "SET_XUR_DATA",
  RESET_PLAYER_DATA: "RESET_PLAYER_DATA"
};

export const loadoutActionTypes = {
  SET_LOADOUT_DATA: "SET_LOADOUT_DATA",
  RESET_LOADOUT: "RESET_LOADOUT"
};

export const crucibleActionTypes = {
  SET_CRUCIBLE_DATA: "SET_CRUCIBLE_DATA",
  SET_CRUCIBLE_MATCHES: "SET_CRUCIBLE_MATCHES",
  RESET_CRUCIBLE_DATA: "RESET_CRUCIBLE_DATA"
};

export const gambitActionTypes = {
  SET_GAMBIT_DATA: "SET_GAMBIT_DATA",
  SET_GAMBIT_MATCHES: "SET_GAMBIT_MATCHES",
  RESET_GAMBIT_DATA: "RESET_GAMBIT_DATA"
};

export const raidActionTypes = {
  SET_RAID_DATA: "SET_RAID_DATA",
  UPDATE_RAID_BADGES: "UPDATE_RAID_BADGES",
  FAIL_UPDATE_RAID_BADGES: "FAIL_UPDATE_RAID_BADGES",
  SET_RAID_BADGES: "SET_RAID_BADGES",
  RESET_RAID_DATA: "RESET_RAID_DATA"
};
