export const globalActionTypes = {
  SET_LOADER: "SET_LOADER",
  SET_ERROR: "SET_ERROR"
};
export const loadoutActionTypes = {
  SET_LOADOUT_DATA: "SET_LOADOUT_DATA",
  RESET_LOADOUT: "RESET_LOADOUT"
};
export const crucibleActionTypes = {
  SET_CRUCIBLE_DATA: "SET_CRUCIBLE_DATA",
  SET_CRUCIBLE_MATCHES: "SET_CRUCIBLE_MATCHES",
  RESET_CRUCIBLE_DATA: "RESET_CRUCIBLE_DATA"
};
